// Deploy Service - Generate deployment packages
import JSZip from 'jszip';
import { ToolManifest, ToolConfig } from '../data/toolsManifest';

export interface DeploymentPackage {
  toolId: string;
  toolName: string;
  envFile: string;
  runScript: string;
  readmeContent: string;
  zipBlob?: Blob;
}

// Generate .env file content
export function generateEnvFile(tool: ToolManifest, configValues: Record<string, string>): string {
  const lines: string[] = [
    `# Environment configuration for ${tool.name}`,
    `# Generated by Fabric Toolbox Dashboard`,
    `# ${new Date().toISOString()}`,
    '',
  ];

  tool.config.forEach(c => {
    const value = configValues[c.name] || '';
    const comment = c.description ? `# ${c.description}` : '';
    if (comment) lines.push(comment);
    if (c.required && !value) {
      lines.push(`# REQUIRED - Please fill in:`);
    }
    lines.push(`${c.name.toUpperCase()}=${value}`);
    lines.push('');
  });

  return lines.join('\n');
}

// Generate run script
export function generateRunScript(tool: ToolManifest, configValues: Record<string, string>): string {
  const lines: string[] = [
    '#!/bin/bash',
    '',
    `# Run script for ${tool.name}`,
    `# Generated by Fabric Toolbox Dashboard`,
    `# ${new Date().toISOString()}`,
    '',
    '# Exit on error',
    'set -e',
    '',
    '# Load environment variables if .env exists',
    'if [ -f .env ]; then',
    '  export $(cat .env | grep -v "^#" | xargs)',
    'fi',
    '',
  ];

  // Add prerequisite checks
  if (tool.prerequisites.length > 0) {
    lines.push('# Check prerequisites');
    tool.prerequisites.forEach(p => {
      if (p.checkCmd) {
        lines.push(`echo "Checking ${p.name}..."`);
        lines.push(`if ! ${p.checkCmd} > /dev/null 2>&1; then`);
        lines.push(`  echo "Error: ${p.name} is not installed"`);
        if (p.installCmd) {
          lines.push(`  echo "Install with: ${p.installCmd}"`);
        }
        if (p.url) {
          lines.push(`  echo "See: ${p.url}"`);
        }
        lines.push('  exit 1');
        lines.push('fi');
      }
    });
    lines.push('');
  }

  // Add run instructions as commands
  lines.push('# Run steps');
  tool.runInstructions.forEach(r => {
    lines.push(`echo "Step ${r.step}: ${r.description}"`);
    if (r.command) {
      let cmd = r.command;
      // Replace config placeholders with environment variable references
      tool.config.forEach(c => {
        const envVar = c.name.toUpperCase();
        cmd = cmd.replace(new RegExp(`\\$\\{?${c.name}\\}?`, 'g'), `\${${envVar}}`);
      });
      if (r.isOptional) {
        lines.push(`# Optional step - uncomment to run:`);
        lines.push(`# ${cmd}`);
      } else {
        lines.push(cmd);
      }
    }
    lines.push('');
  });

  lines.push('echo "Done!"');

  return lines.join('\n');
}

// Generate Windows batch script
export function generateBatchScript(tool: ToolManifest, configValues: Record<string, string>): string {
  const lines: string[] = [
    '@echo off',
    '',
    `REM Run script for ${tool.name}`,
    `REM Generated by Fabric Toolbox Dashboard`,
    '',
    'REM Load environment variables from .env if it exists',
    'if exist .env (',
    '  for /f "tokens=*" %%i in (.env) do (',
    '    set %%i',
    '  )',
    ')',
    '',
  ];

  // Add run instructions
  lines.push('REM Run steps');
  tool.runInstructions.forEach(r => {
    lines.push(`echo Step ${r.step}: ${r.description}`);
    if (r.command && !r.isOptional) {
      let cmd = r.command;
      // Convert bash-style variables to batch style
      tool.config.forEach(c => {
        const envVar = c.name.toUpperCase();
        cmd = cmd.replace(new RegExp(`\\$\\{?${c.name}\\}?`, 'g'), `%${envVar}%`);
      });
      // Convert common commands
      cmd = cmd.replace(/^pip /g, 'pip ');
      cmd = cmd.replace(/^python /g, 'python ');
      cmd = cmd.replace(/^npm /g, 'npm ');
      lines.push(cmd);
    }
    lines.push('');
  });

  lines.push('echo Done!');
  lines.push('pause');

  return lines.join('\r\n');
}

// Generate README content
export function generateReadme(tool: ToolManifest, configValues: Record<string, string>): string {
  const lines: string[] = [
    `# ${tool.name}`,
    '',
    `> ${tool.description}`,
    '',
    '---',
    '',
    '## Quick Start',
    '',
    '### 1. Configure',
    '',
    'Edit the `.env` file with your configuration values:',
    '',
    '```bash',
    '# Open and edit .env with your values',
    'nano .env',
    '```',
    '',
    '### 2. Run',
    '',
    '**On macOS/Linux:**',
    '```bash',
    'chmod +x run.sh',
    './run.sh',
    '```',
    '',
    '**On Windows:**',
    '```cmd',
    'run.bat',
    '```',
    '',
    '---',
    '',
    '## Prerequisites',
    '',
  ];

  tool.prerequisites.forEach(p => {
    lines.push(`- **${p.name}**`);
    if (p.installCmd) {
      lines.push(`  - Install: \`${p.installCmd}\``);
    }
    if (p.url) {
      lines.push(`  - [Documentation](${p.url})`);
    }
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Configuration Reference');
  lines.push('');
  lines.push('| Parameter | Required | Description | Default |');
  lines.push('|-----------|----------|-------------|---------|');

  tool.config.forEach(c => {
    const required = c.required ? '✅' : '';
    const defaultVal = c.default || '-';
    lines.push(`| \`${c.name}\` | ${required} | ${c.description} | ${defaultVal} |`);
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Step-by-Step Instructions');
  lines.push('');

  tool.runInstructions.forEach(r => {
    const optional = r.isOptional ? ' *(optional)*' : '';
    lines.push(`### Step ${r.step}: ${r.description}${optional}`);
    lines.push('');
    if (r.command) {
      lines.push('```bash');
      lines.push(r.command);
      lines.push('```');
      lines.push('');
    }
  });

  if (tool.output) {
    lines.push('---');
    lines.push('');
    lines.push('## Expected Output');
    lines.push('');
    lines.push(tool.output);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Tool Location');
  lines.push('');
  lines.push(`Source files are located at: \`${tool.path}\``);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [Fabric Toolbox Dashboard](https://github.com/microsoft/fabric-toolbox)*');

  return lines.join('\n');
}

// Generate complete deployment package as ZIP
export async function generateDeploymentZip(
  tool: ToolManifest,
  configValues: Record<string, string>
): Promise<Blob> {
  const zip = new JSZip();

  // Create folder with tool name
  const folderName = `${tool.id}-deployment`;
  const folder = zip.folder(folderName)!;

  // Add .env file
  const envContent = generateEnvFile(tool, configValues);
  folder.file('.env', envContent);

  // Add run scripts
  const runShContent = generateRunScript(tool, configValues);
  folder.file('run.sh', runShContent);

  const runBatContent = generateBatchScript(tool, configValues);
  folder.file('run.bat', runBatContent);

  // Add README
  const readmeContent = generateReadme(tool, configValues);
  folder.file('README.md', readmeContent);

  // Generate the ZIP blob
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  return blob;
}

// Download the ZIP file
export async function downloadDeploymentZip(
  tool: ToolManifest,
  configValues: Record<string, string>
): Promise<void> {
  const blob = await generateDeploymentZip(tool, configValues);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${tool.id}-deployment.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ============ GIT PUSH INTEGRATION ============

export interface GitConfig {
  repoUrl: string;
  branch: string;
  commitMessage: string;
  accessToken?: string;
}

// Generate Git push script
export function generateGitPushScript(
  tool: ToolManifest,
  configValues: Record<string, string>,
  gitConfig: GitConfig
): string {
  const folderName = `${tool.id}-deployment`;

  const lines: string[] = [
    '#!/bin/bash',
    '',
    `# Git deployment script for ${tool.name}`,
    `# Generated by Fabric Toolbox Dashboard`,
    '',
    'set -e',
    '',
    '# Configuration',
    `REPO_URL="${gitConfig.repoUrl}"`,
    `BRANCH="${gitConfig.branch}"`,
    `FOLDER="${folderName}"`,
    '',
    '# Clone or update repo',
    'if [ -d "repo" ]; then',
    '  cd repo',
    '  git pull origin $BRANCH',
    'else',
    '  git clone $REPO_URL repo',
    '  cd repo',
    '  git checkout -B $BRANCH',
    'fi',
    '',
    '# Copy deployment files',
    `mkdir -p $FOLDER`,
    `cp ../.env $FOLDER/`,
    `cp ../run.sh $FOLDER/`,
    `cp ../run.bat $FOLDER/`,
    `cp ../README.md $FOLDER/`,
    '',
    '# Commit and push',
    'git add .',
    `git commit -m "${gitConfig.commitMessage}"`,
    'git push origin $BRANCH',
    '',
    'echo "Pushed to $REPO_URL on branch $BRANCH"',
  ];

  return lines.join('\n');
}

// Generate ZIP with Git push script included
export async function generateDeploymentZipWithGit(
  tool: ToolManifest,
  configValues: Record<string, string>,
  gitConfig?: GitConfig
): Promise<Blob> {
  const zip = new JSZip();
  const folderName = `${tool.id}-deployment`;
  const folder = zip.folder(folderName)!;

  // Add standard files
  folder.file('.env', generateEnvFile(tool, configValues));
  folder.file('run.sh', generateRunScript(tool, configValues));
  folder.file('run.bat', generateBatchScript(tool, configValues));
  folder.file('README.md', generateReadme(tool, configValues));

  // Add Git push script if config provided
  if (gitConfig) {
    const gitScript = generateGitPushScript(tool, configValues, gitConfig);
    folder.file('git-push.sh', gitScript);
  }

  return zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });
}
